-- MySQL Script generated by MySQL Workbench
-- 09/07/2017 21:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BANK
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BANK` ;

-- -----------------------------------------------------
-- Schema BANK
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BANK` DEFAULT CHARACTER SET utf8 ;
USE `BANK` ;

-- -----------------------------------------------------
-- Table `BANK`.`CUSTOMERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BANK`.`CUSTOMERS` ;

CREATE TABLE IF NOT EXISTS `BANK`.`CUSTOMERS` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `age` VARCHAR(20) NULL,
  `sex` VARCHAR(10) NULL,
  `region` VARCHAR(20) NULL,
  `income` VARCHAR(20) NULL,
  `married` VARCHAR(5) NULL,
  `children` VARCHAR(5) NULL,
  `car` VARCHAR(5) NULL,
  `save_act` VARCHAR(5) NULL,
  `current_act` VARCHAR(5) NULL,
  `mortgage` VARCHAR(5) NULL,
  `pep` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `BANK`.`CUSTOMERS`
-- -----------------------------------------------------
START TRANSACTION;
USE `BANK`;
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(1,'Maria Gerrero Santamaria','0_34','MALE','SUBURBAN','0_24386','NO','3','NO','YES','YES','YES');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(2,'Cristian Pérez Marquez','0_34','FEMALE','TOWN','0_24386','YES','0','YES','YES','NO','YES');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(3,'Jesus Baena Trigo','35_51','MALE','SUBURBAN','0_24386','YES','0','YES','YES','YES','YES');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(4,'Ana García Belen','35_51','FEMALE','INNER_CITY','0_24386','YES','1','NO','NO','YES','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(5,'Pedro Antunez Fernández','0_34','MALE','INNER_CITY','0_24386','NO','2','NO','YES','NO','YES');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(6,'Jose Santiago Ramirez','0_34','FEMALE','RURAL','0_24386','YES','0','NO','YES','YES','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(7,'Petra Perea Vals','35_51','MALE','RURAL','24387_43758','YES','0','YES','YES','YES','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(8,'Juana Gil Roa','52_max','FEMALE','TOWN','24387_43758','YES','0','NO','YES','YES','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(9,'Verónica Álamo Suarez','35_51','FEMALE','TOWN','24387_43758','YES','2','NO','NO','YES','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(10,'Sebastian Jaen Sanchez','52_max','MALE','RURAL','43759_max','YES','3','YES','YES','NO','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(11,'Esther Pino Gutierrez','35_51','MALE','TOWN','24387_43758','YES','1','NO','NO','YES','YES');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(12,'Francisca Fernandez Sanchez','0_34','MALE','INNER_CITY','0_24386','YES','1','NO','NO','NO','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(13,'Isabel López Martinez','0_34','FEMALE','INNER_CITY','0_24386','YES','0','NO','YES','YES','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(14,'Adrian Novoa Cavanas','52_max','MALE','INNER_CITY','43759_max','YES','1','YES','YES','NO','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(15,'Demetrio Alvarez Mendez','35_51','FEMALE','INNER_CITY','24387_43758','YES','3','NO','YES','YES','YES');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(16,'Vanesa Córdoba Roa','0_34','FEMALE','INNER_CITY','0_24386','YES','3','NO','YES','YES','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(17,'Beatriz Díez García','35_51','FEMALE','INNER_CITY','24387_43758','NO','2','NO','YES','YES','YES');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(18,'Samuel Soto Benitez','35_51','MALE','TOWN','0_24386','YES','0','NO','YES','YES','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(19,'Agustina Blasco Mercado','52_max','MALE','SUBURBAN','43759_max','YES','2','NO','YES','YES','NO');
INSERT INTO `BANK`.`CUSTOMERS` (`id`, `name`, `age`, `sex`, `region`, `income`, `married`, `children`, `car`, `save_act`, `current_act`, `mortgage`)VALUES(20,'Luis Manuel Perea Prieto','52_max','FEMALE','RURAL','24387_43758','YES','3','YES','YES','YES','YES');


COMMIT;